'use client';

import { useEffect, useState } from 'react';

import { Button } from '@/components/ui/button';
import { Card, CardHeader, ErrorState, Skeleton } from '@/components/ui/primitives';
import { ApiError, fetchReport, reportPdfUrl } from '@/lib/api';
import { formatDateTime } from '@/lib/format';
import type { InvestigationDetail } from '@/lib/types';

interface Report {
  title: string;
  reference: string;
  generated_at: string;
  sections: string[];
  markdown: string;
}

/**
 * The assessment report.
 *
 * Assembled server-side from stored rows rather than generated by a model: by
 * this point every judgement has already been made, reviewed and recorded, so
 * writing fresh prose here would risk the report saying something the
 * assessment does not.
 */
export function ReportPanel({
  caseId,
  investigation,
}: {
  caseId: string;
  investigation: InvestigationDetail;
}) {
  const [report, setReport] = useState<Report | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchReport(caseId, investigation.id)
      .then((data) => {
        if (!cancelled) setReport(data);
      })
      .catch((exc) => {
        if (!cancelled) {
          setError(
            exc instanceof ApiError ? exc.message : 'The report could not be generated.',
          );
        }
      });
    return () => {
      cancelled = true;
    };
  }, [caseId, investigation.id]);

  if (error) {
    return <ErrorState title="Report unavailable" detail={error} />;
  }

  if (!report) {
    return (
      <Card>
        <Skeleton className="h-5 w-64" />
        <Skeleton className="mt-3 h-3 w-full" />
        <Skeleton className="mt-2 h-3 w-11/12" />
        <Skeleton className="mt-2 h-3 w-10/12" />
        <Skeleton className="mt-6 h-4 w-40" />
        <Skeleton className="mt-3 h-3 w-full" />
        <Skeleton className="mt-2 h-3 w-9/12" />
      </Card>
    );
  }

  return (
    <div className="grid gap-5 lg:grid-cols-4">
      <div className="lg:col-span-3">
        <Card>
          <CardHeader
            title={report.title}
            description={`${report.reference} · generated ${formatDateTime(report.generated_at)}`}
            actions={
              <div className="no-print flex gap-2">
                <a
                  href={reportPdfUrl(caseId, investigation.id)}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex h-8 items-center rounded border border-line-strong bg-surface px-3 text-xs font-medium text-ink hover:bg-raised"
                >
                  Download PDF
                </a>
                <Button size="md" onClick={() => window.print()}>
                  Print
                </Button>
              </div>
            }
          />
          <article className="prose-report mt-5 max-w-none text-sm">
            <MarkdownReport markdown={report.markdown} />
          </article>
        </Card>
      </div>

      <div className="no-print">
        <Card className="sticky top-0">
          <CardHeader title="Contents" />
          <ol className="mt-3 space-y-1.5 text-xs">
            {report.sections.map((section, index) => (
              <li key={section} className="flex gap-2 text-ink-muted">
                <span className="tabular w-4 shrink-0 text-ink-subtle">{index + 1}</span>
                {section}
              </li>
            ))}
          </ol>
          <p className="mt-4 border-t border-line pt-3 text-2xs leading-relaxed text-ink-subtle">
            Sections with nothing to report print &quot;none recorded&quot; rather than being
            omitted, so a reader can tell the difference between nothing found and nothing
            checked.
          </p>
        </Card>
      </div>
    </div>
  );
}

/**
 * Minimal Markdown renderer for the report's known structure.
 *
 * The report is produced by this application in a fixed shape - headings,
 * bullets, tables, bold and code - so a small purpose-built renderer is more
 * appropriate than a general Markdown dependency, and it cannot render raw HTML
 * from the document corpus.
 */
function MarkdownReport({ markdown }: { markdown: string }) {
  const blocks: React.ReactNode[] = [];
  const lines = markdown.split('\n');
  let listBuffer: string[] = [];
  let tableBuffer: string[][] = [];

  const flushList = (key: string) => {
    if (listBuffer.length === 0) return;
    blocks.push(
      <ul key={key}>
        {listBuffer.map((item, index) => (
          <li key={index}>{inline(item)}</li>
        ))}
      </ul>,
    );
    listBuffer = [];
  };

  const flushTable = (key: string) => {
    if (tableBuffer.length === 0) return;
    const [header, ...rows] = tableBuffer;
    blocks.push(
      <div key={key} className="scroll-slim overflow-x-auto">
        <table>
          <thead>
            <tr>
              {(header ?? []).map((cell, index) => (
                <th key={index}>{inline(cell)}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, rowIndex) => (
              <tr key={rowIndex}>
                {row.map((cell, cellIndex) => (
                  <td key={cellIndex}>{inline(cell)}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>,
    );
    tableBuffer = [];
  };

  lines.forEach((raw, index) => {
    const line = raw.trimEnd();
    const trimmed = line.trim();

    if (trimmed.startsWith('|')) {
      flushList(`l-${index}`);
      const cells = trimmed
        .replace(/^\|/, '')
        .replace(/\|$/, '')
        .split('|')
        .map((cell) => cell.trim());
      if (cells.every((cell) => /^[-: ]*$/.test(cell))) return;
      tableBuffer.push(cells);
      return;
    }
    flushTable(`t-${index}`);

    if (trimmed.startsWith('- ')) {
      listBuffer.push(trimmed.slice(2));
      return;
    }
    flushList(`l-${index}`);

    if (!trimmed) return;
    if (trimmed.startsWith('### ')) {
      blocks.push(<h3 key={index}>{inline(trimmed.slice(4))}</h3>);
    } else if (trimmed.startsWith('## ')) {
      blocks.push(<h2 key={index}>{inline(trimmed.slice(3))}</h2>);
    } else if (trimmed.startsWith('# ')) {
      blocks.push(<h1 key={index}>{inline(trimmed.slice(2))}</h1>);
    } else {
      blocks.push(<p key={index}>{inline(trimmed)}</p>);
    }
  });

  flushList('l-end');
  flushTable('t-end');

  return <>{blocks}</>;
}

/** Renders bold, code and italic runs. Everything else is plain text. */
function inline(text: string): React.ReactNode {
  const tokens = text.split(/(\*\*[^*]+\*\*|`[^`]+`|_[^_]+_)/g).filter(Boolean);
  return tokens.map((token, index) => {
    if (token.startsWith('**') && token.endsWith('**')) {
      return <strong key={index}>{token.slice(2, -2)}</strong>;
    }
    if (token.startsWith('`') && token.endsWith('`')) {
      return <code key={index}>{token.slice(1, -1)}</code>;
    }
    if (token.startsWith('_') && token.endsWith('_') && token.length > 2) {
      return <em key={index}>{token.slice(1, -1)}</em>;
    }
    return <span key={index}>{token}</span>;
  });
}
