"""initial schema

Revision ID: aca28ca0a1e6
Revises:
Create Date: 2026-09-05 17:34:42.449471

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aca28ca0a1e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=96), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("before", sa.JSON(), nullable=False),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_case_time", ["case_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_investigation_id"), ["investigation_id"], unique=False
        )

    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("organisation", sa.String(length=200), nullable=False),
        sa.Column("review_type", sa.String(length=120), nullable=False),
        sa.Column("domain_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("analyst", sa.String(length=120), nullable=False),
        sa.Column("sector", sa.String(length=120), nullable=False),
        sa.Column("jurisdiction", sa.String(length=120), nullable=False),
        sa.Column("background", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_reference"), ["reference"], unique=True)
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("model_backend", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("demo_mode", sa.Boolean(), nullable=False),
        sa.Column("total_cases", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("errored", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_runs_created_at"), ["created_at"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("doc_kind", sa.String(length=16), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_documents_doc_kind"), ["doc_kind"], unique=False)

    op.create_table(
        "eval_results",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("actual", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["eval_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_results_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_results_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_results_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_eval_results_suite"), ["suite"], unique=False)

    op.create_table(
        "investigations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("domain_key", sa.String(length=64), nullable=False),
        sa.Column("model_backend", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("demo_mode", sa.Boolean(), nullable=False),
        sa.Column("retrieval_quality", sa.Float(), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("overall_level", sa.String(length=16), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("evidence_strength", sa.String(length=16), nullable=False),
        sa.Column("score_factors", sa.JSON(), nullable=False),
        sa.Column("category_levels", sa.JSON(), nullable=False),
        sa.Column("coverage", sa.JSON(), nullable=False),
        sa.Column("narrative", sa.JSON(), nullable=False),
        sa.Column("escalation_reasons", sa.JSON(), nullable=False),
        sa.Column("integrity", sa.JSON(), nullable=False),
        sa.Column("rejected_evidence", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigations_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigations_status"), ["status"], unique=False)

    op.create_table(
        "challenges",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("challenge_id", sa.String(length=64), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("challenge_type", sa.String(length=40), nullable=False),
        sa.Column("argument", sa.Text(), nullable=False),
        sa.Column("counter_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("suggested_revision", sa.Text(), nullable=False),
        sa.Column("proposed_severity", sa.String(length=20), nullable=False),
        sa.Column("unresolved", sa.Boolean(), nullable=False),
        sa.Column("on_demand", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_challenges_challenge_type"), ["challenge_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_challenges_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_challenges_risk_id"), ["risk_id"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("section_number", sa.String(length=32), nullable=False),
        sa.Column("section_title", sa.String(length=200), nullable=False),
        sa.Column("citation_key", sa.String(length=120), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chunks_document_id"), ["document_id"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("document_name", sa.String(length=200), nullable=False),
        sa.Column("section_reference", sa.String(length=120), nullable=False),
        sa.Column("chunk_id", sa.String(length=96), nullable=False),
        sa.Column("materiality", sa.String(length=20), nullable=False),
        sa.Column("grounding_score", sa.Float(), nullable=False),
        sa.Column("is_grounded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_evidence_id"), ["evidence_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_evidence_investigation_id"), ["investigation_id"], unique=False
        )

    op.create_table(
        "investigation_steps",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("step_id", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("prompt_reference", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("investigation_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_investigation_steps_investigation_id"),
            ["investigation_id"],
            unique=False,
        )

    op.create_table(
        "overrides",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("ai_value", sa.String(length=120), nullable=False),
        sa.Column("human_value", sa.String(length=120), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("overrides", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_overrides_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_overrides_risk_id"), ["risk_id"], unique=False)

    op.create_table(
        "policy_matches",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("clause_reference", sa.String(length=60), nullable=False),
        sa.Column("clause_title", sa.String(length=200), nullable=False),
        sa.Column("relevance", sa.Text(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("threshold_assessment", sa.Text(), nullable=False),
        sa.Column("sufficiency_caveat", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_policy_matches_clause_reference"), ["clause_reference"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_policy_matches_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_policy_matches_risk_id"), ["risk_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_policy_matches_trigger_type"), ["trigger_type"], unique=False
        )

    op.create_table(
        "reviews",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("ai_overall_level", sa.String(length=16), nullable=False),
        sa.Column("final_overall_level", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_decision"), ["decision"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reviews_investigation_id"), ["investigation_id"], unique=False
        )

    op.create_table(
        "risks",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ai_severity", sa.String(length=20), nullable=False),
        sa.Column("ai_likelihood", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("likelihood", sa.String(length=20), nullable=False),
        sa.Column("supporting_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("contradicting_evidence_ids", sa.JSON(), nullable=False),
        sa.Column("assumptions", sa.JSON(), nullable=False),
        sa.Column("open_questions", sa.JSON(), nullable=False),
        sa.Column("mitigating_factors", sa.JSON(), nullable=False),
        sa.Column("evidence_strength", sa.String(length=20), nullable=False),
        sa.Column("strength_rationale", sa.Text(), nullable=False),
        sa.Column("inherent_score", sa.Float(), nullable=False),
        sa.Column("adjusted_score", sa.Float(), nullable=False),
        sa.Column("mind_changer_increase", sa.Text(), nullable=False),
        sa.Column("mind_changer_decrease", sa.Text(), nullable=False),
        sa.Column("is_false_positive", sa.Boolean(), nullable=False),
        sa.Column("analyst_note", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_risks_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_risks_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_risks_risk_id"), ["risk_id"], unique=False)

    op.create_table(
        "verifications",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("verification_id", sa.String(length=64), nullable=False),
        sa.Column("risk_id", sa.String(length=64), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("citations_checked", sa.JSON(), nullable=False),
        sa.Column("irrelevant_citation_ids", sa.JSON(), nullable=False),
        sa.Column("downgrade_recommended", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["investigation_id"], ["investigations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verifications_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_verifications_risk_id"), ["risk_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_verifications_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verifications_status"))
        batch_op.drop_index(batch_op.f("ix_verifications_risk_id"))
        batch_op.drop_index(batch_op.f("ix_verifications_investigation_id"))

    op.drop_table("verifications")
    with op.batch_alter_table("risks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risks_risk_id"))
        batch_op.drop_index(batch_op.f("ix_risks_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_risks_category"))

    op.drop_table("risks")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_decision"))

    op.drop_table("reviews")
    with op.batch_alter_table("policy_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_matches_trigger_type"))
        batch_op.drop_index(batch_op.f("ix_policy_matches_risk_id"))
        batch_op.drop_index(batch_op.f("ix_policy_matches_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_policy_matches_clause_reference"))

    op.drop_table("policy_matches")
    with op.batch_alter_table("overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_overrides_risk_id"))
        batch_op.drop_index(batch_op.f("ix_overrides_investigation_id"))

    op.drop_table("overrides")
    with op.batch_alter_table("investigation_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigation_steps_investigation_id"))

    op.drop_table("investigation_steps")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_evidence_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_document_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_category"))

    op.drop_table("evidence")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_document_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenges_risk_id"))
        batch_op.drop_index(batch_op.f("ix_challenges_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_challenges_challenge_type"))

    op.drop_table("challenges")
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigations_status"))
        batch_op.drop_index(batch_op.f("ix_investigations_case_id"))

    op.drop_table("investigations")
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_results_suite"))
        batch_op.drop_index(batch_op.f("ix_eval_results_run_id"))
        batch_op.drop_index(batch_op.f("ix_eval_results_category"))
        batch_op.drop_index(batch_op.f("ix_eval_results_case_id"))

    op.drop_table("eval_results")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_doc_kind"))
        batch_op.drop_index(batch_op.f("ix_documents_case_id"))

    op.drop_table("documents")
    with op.batch_alter_table("eval_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_runs_created_at"))

    op.drop_table("eval_runs")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_status"))
        batch_op.drop_index(batch_op.f("ix_cases_reference"))

    op.drop_table("cases")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_case_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))
        batch_op.drop_index("ix_audit_case_time")

    op.drop_table("audit_events")
    # ### end Alembic commands ###
